CREATE TABLE PROCESO.PUNTO4 AS
WITH T1 AS (
SELECT
canrocta,
COUNT(canrocta) AS CANTIDAD
FROM proceso.PPCuentas
INNER JOIN PROCESO.TARJETAS_ACTIVAS ON
CANROTRJ = TJNROTRJ
AND caestcta = "ACTIVA"
AND tjettrj = "ACTIVA"
GROUP BY 1
ORDER BY COUNT(canrocta) DESC
LIMIT 10
)
SELECT 
canrocta,
CANTIDAD
FROM T1
ORDER BY 2