CREATE TABLE PROCESO.PUNTO6 AS
WITH T1 AS (
SELECT
ciudad_residencia,
edad_cli,
CASE WHEN edad_cli BETWEEN 0 AND 10 THEN "1 A 10"
WHEN edad_cli BETWEEN 11 AND 20 THEN "11 A 20"
WHEN edad_cli BETWEEN 21 AND 30 THEN "21 A 30"
WHEN edad_cli BETWEEN 31 AND 40 THEN "31 A 40"
WHEN edad_cli BETWEEN 41 AND 50 THEN "41 A 50"
WHEN edad_cli BETWEEN 51 AND 60 THEN "51 A 60" 
WHEN edad_cli BETWEEN 61 AND 70 THEN "61 A 70"
WHEN edad_cli BETWEEN 71 AND 80 THEN "71 A 80"
WHEN edad_cli BETWEEN 81 AND 90 THEN "81 A 90"
WHEN edad_cli BETWEEN 91 AND 120 THEN "MAYOR DE 91" ELSE "NONE" END AS RANGO_EDAD
FROM proceso.TARJETAS_ACTIVAS
INNER JOIN proceso.PPclientes ON
TJNRODOC = NUM_DOC
AND COD_TIPO_DOC = tjclsdoc
AND tjesttrj = "ACTIVA"
AND SEGMENTO NOT IN ("PYMES","EMPRESARIAL","CONSTRUCTOR CORPORATIVO")
AND edad_cli > 1
AND edad_cli < 120
)
SELECT ciudad_residencia,
RANGO_EDAD,
COUNT(RANGO_EDAD) AS TARJETAS_ACTIVAS
FROM T1
GROUP BY 1, 2
ORDER BY ciudad_residencia, RANGO_EDAD DESC;